### ISSUE TITLE
How to get username and password for developer account?

### ISSUE THREAD

**Issue by adil82pk** [Trulioo/sdk-csharp-v1#10]
//Example Username: JoeNapoli_API_Demo, Example Password: 05uZuPRCyPi!6
            var truliooClient = new TruliooApiClient("JoeNapoli_API_Demo", "05uZuPRCyPi!6");

**Comment by dbraaten42** [comment]
You need to contact sales for the full Global Gateway experience using this SDK.  If you are a smaller organization you may be able to use https://www.trulioo.com/developers
